### ISSUE TITLE
next_page doesn't respect where clause

### ISSUE THREAD

**Issue by mamstergrub** [TrevorHinesley/moonclerk#1]
Hello! I'm using the moonclerk gem to request last quarter's payments as follows:

`payments = Moonclerk::Payment.where( status: "successful", date_from: from, date_to: to, count: 100 )`

This works fine. However, if I page through the results using `auto_paging_each`, it continues returning results outside of the specified date range. I believe the problem is with the `next_page` function; I tried stepping through manually using `payments = payments.next_page` and quickly stepped outside the date range.

A more minimal example that shows the issue is:

`payments = Moonclerk::Payment.where( date_from: Date.today )`

For my data set, this returns fewer than 10 records, and using next_page returns records from previous dates. Specifying the offset in the query works properly; e.g., if I add `offset: 10` to this query, it returns an empty set.

It looks like either (a) I'm using the module wrong, which is more than possible, or (b) the class instance is storing the count and offset but not persisting the rest of the where() clause.

**Comment by TrevorHinesley** [comment]
Apologies for not replying to this years ago. I don't actively maintain this but hadn't made it private. Archiving :)
